#heartbeat.autodiscover:
#  # Autodiscover pods
#  providers:
#    - type: kubernetes
#      resource: pod
#      scope: cluster
#      node: ${NODE_NAME}
#      hints.enabled: true
#
#  # Autodiscover services
#  providers:
#    - type: kubernetes
#      resource: service
#      scope: cluster
#      node: ${NODE_NAME}
#      hints.enabled: true
#
#  # Autodiscover nodes
#  providers:
#    - type: kubernetes
#      resource: node
#      node: ${NODE_NAME}
#      scope: cluster
#      templates:
#        # Example, check SSH port of all cluster nodes:
#        - condition: ~
#          config:
#            - hosts:
#                - ${data.host}:22
#              name: ${data.kubernetes.node.name}
#              schedule: '@every 10s'
#              timeout: 5s
#              type: tcp
heartbeat.monitors:
- type: http
  name: Grafana
  hosts: ["http://192.168.1.190:3000"]
  schedule: '@every 60s'
  check.response.status: [404]
- type: http
  name: Portainer
  hosts: ["http://192.168.1.190:9000"]
  schedule: '@every 60s'
  check.response.status: [200]


processors:
  - add_cloud_metadata:

cloud.id: ${ELASTIC_CLOUD_ID}
cloud.auth: ${ELASTIC_CLOUD_AUTH}

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}